### ISSUE TITLE
Missing APEX_format.sty in root directory.

### ISSUE THREAD

**Issue by yannlamontagne** [APEXCalculus/APEXCalculus_Source#1]
Missing APEX_format.sty in root directory.

**Comment by KellyBlack** [comment]
There is an APEX_format.sty file in the  Fundamentals-of-Matrix-Algebra repo. Can it just be copied over?

**Comment by yannlamontagne** [comment]
Yes, I guess but probably it should also be added to the cal repository.

Also I am wondering if its the same for both books?

Since when I try to compile with the APEX_format.sty file of Fundamentals-of-Matrix-Algebra.  My compiler can not find: \myincludegraphics

! Undefined control sequence.
<argument> ...idth }\centering \myincludegraphics
                                                  []{figures/figZoomSinXOver...

**Comment by hartmangn** [comment]
Fixed for Version 3.0. The .sty file found the Matrix Algebra folder is indeed much, much different.
